### ISSUE TITLE
SAM with PyTorch Lightning

### ISSUE THREAD

**Issue by AlbertoSabater** [davda54/sam#31]
Hi, I have implemented SAM to be used along with PyTorch Lightning, but it crashes at the beginning of the training:

This is a resume of the key lines of my LightningModule that involve SAM:
```
class pl_module(LightningModule):
    def __init__(self, params...):
        super().__init__()
        self.save_hyperparameters()
        self.automatic_optimization = False

    def configure_optimizers(self):
        optim = SAM(self.parameters(), SGD, lr=0.01)
        return optim

    def training_step(self, batch, batch_idx):
        optimizer = self.optimizers()
        def closure():
            loss = self.compute_loss(batch)
            self.manual_backward(loss, optimizer)
            return loss

        loss = self.compute_loss(batch)
        self.manual_backward(loss, optimizer)
        optimizer.optimizer.step(closure=closure)
        optimizer.optimizer.zero_grad()

        return loss 
```

This is the error:
```
Traceback (most recent call last):
  File "trainer_v2.py", line 409, in <module>
    train(folder_name, path_results, data_params, backbone_params, clf_params, contrastive_params, 
  File "trainer_v2.py", line 311, in train
    trainer.fit(model, dm)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
    self.train_loop.run_training_epoch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 499, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 714, in run_training_batch
    self.training_step_and_backward(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 823, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 290, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 204, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 155, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "trainer_v2.py", line 187, in training_step
    optimizer.second_step(zero_grad=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/asabater/2021_projects/evnet/sam.py", line 34, in second_step
    p.sub_(self.state[p]["e_w"])  # get back to "w" from "w + e(w)"
KeyError: 'e_w'
```

**Comment by AlbertoSabater** [comment]
I managed to solve this issue. The code above has been updated, but the main problem was related to the libraries installation in a docker image.

In case you want to write a brief tutorial for PyTorch Lightning, the _training_step_ code can be also written as:
```
    def training_step(self, batch, batch_idx):
            optimizer = self.optimizers()

            # first forward-backward pass
            loss_1 = self.compute_loss(batch)
            self.manual_backward(loss_1 , optimizer)
            optimizer.first_step(zero_grad=True)

            # second forward-backward pass
            loss_2 = self.compute_loss(batch)
            self.manual_backward(loss_2 , optimizer)
            optimizer.second_step(zero_grad=True)

            return loss_1
```

**Comment by davda54** [comment]
Thanks for sharing the code! I will add it to the readme file :)

**Comment by DanTaranis** [comment]
@davda54 
I'm getting the following errors:
```
TypeError: 'LightningSAM' object is not iterable
```
```
    def validation_step(self, batch, batch_idx):
        optimizer = self.optimizers()

        # first forward-backward pass
        loss_1, y, y_pred = self.compute_batch(batch)
        # loss_1.backward()
        self.manual_backward(loss_1, optimizer)
        optimizer.first_step(zero_grad=True)

        # second forward-backward pass
        loss_2, y, y_pred = self.compute_batch(batch)
        # loss_2.backward()
        self.manual_backward(loss_2, optimizer)
        optimizer.second_step(zero_grad=True)



        self.log('loss_val', loss_1)
        return {'loss': loss_1, 'preds': y_pred, 'target': y}
```
